-- No schema change required for "class teacher only" assignment.
-- Enforcement is in application code:
--   GET /api/schools/class-teachers?school_id=
--   POST/PUT /api/classes validates assigned_teacher_id has user_school_roles.role = 'teacher'
--
-- Optional: clear invalid homeroom assignments (gate officers / staff wrongly assigned before this fix)
-- UPDATE school_classes sc
-- SET assigned_teacher_id = NULL
-- WHERE assigned_teacher_id IS NOT NULL
--   AND NOT EXISTS (
--     SELECT 1 FROM teacher_profiles tp
--     JOIN user_school_roles usr ON usr.user_id = tp.user_id AND usr.school_id = tp.school_id
--     WHERE tp.id = sc.assigned_teacher_id
--       AND usr.role = 'teacher'
--       AND usr.is_active = true
--   );
